/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.CardLayout;

/**
 *
 * @author tony
 */
public class TelaCardLayout extends javax.swing.JFrame {

    /**
     * Creates new form TelaCardLayout
     */
    public TelaCardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPAI = new javax.swing.JPanel();
        jPanelNovembroAzul = new javax.swing.JPanel();
        jPanelOutubroRosa = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuOutubroRosa = new javax.swing.JMenuItem();
        NovembroAzul = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPAI.setLayout(new java.awt.CardLayout());

        jPanelNovembroAzul.setBackground(new java.awt.Color(51, 153, 255));
        jPanelNovembroAzul.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NovembroAzul", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanelNovembroAzul.setForeground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelNovembroAzulLayout = new javax.swing.GroupLayout(jPanelNovembroAzul);
        jPanelNovembroAzul.setLayout(jPanelNovembroAzulLayout);
        jPanelNovembroAzulLayout.setHorizontalGroup(
            jPanelNovembroAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanelNovembroAzulLayout.setVerticalGroup(
            jPanelNovembroAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jPanelPAI.add(jPanelNovembroAzul, "cardNovembro");

        jPanelOutubroRosa.setBackground(new java.awt.Color(255, 204, 204));
        jPanelOutubroRosa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OutubroRosa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 153, 255))); // NOI18N

        javax.swing.GroupLayout jPanelOutubroRosaLayout = new javax.swing.GroupLayout(jPanelOutubroRosa);
        jPanelOutubroRosa.setLayout(jPanelOutubroRosaLayout);
        jPanelOutubroRosaLayout.setHorizontalGroup(
            jPanelOutubroRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanelOutubroRosaLayout.setVerticalGroup(
            jPanelOutubroRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jPanelPAI.add(jPanelOutubroRosa, "cardOutubro");

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_cascade.png"))); // NOI18N
        jMenu1.setText("Tela");

        jMenuOutubroRosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_right.png"))); // NOI18N
        jMenuOutubroRosa.setText("OutubroRosa");
        jMenuOutubroRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOutubroRosaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuOutubroRosa);

        NovembroAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_right.png"))); // NOI18N
        NovembroAzul.setText("NovembroAzul");
        NovembroAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovembroAzulActionPerformed(evt);
            }
        });
        jMenu1.add(NovembroAzul);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuOutubroRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOutubroRosaActionPerformed
        // TODO add your handling code here:
        CardLayout tela= (CardLayout)jPanelPAI.getLayout();
        tela.show(jPanelPAI, "cardOutubro");
         /*Chamamos o PAINEL PAI que é o JPANEL1, e a STRING que tem no PAINEL
        no campo CARD NAME em propriedades do PAINEL FILHO "cardOutubro" */
        
        
    }//GEN-LAST:event_jMenuOutubroRosaActionPerformed

    private void NovembroAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovembroAzulActionPerformed
        // TODO add your handling code here:

        CardLayout tela= (CardLayout)jPanelPAI.getLayout();
        tela.show(jPanelPAI, "cardNovembro");
        /*Chamamos o PAINEL PAI que é o JPANEL1, e a STRING que tem no PAINEL
        no campo CARD NAME em propriedades do PAINEL FILHO "CardNovembro" */
        

    }//GEN-LAST:event_NovembroAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCardLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NovembroAzul;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuOutubroRosa;
    private javax.swing.JPanel jPanelNovembroAzul;
    private javax.swing.JPanel jPanelOutubroRosa;
    private javax.swing.JPanel jPanelPAI;
    // End of variables declaration//GEN-END:variables
}
